routes/web.php
<?php

use App\Http\Controllers\AnswerController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LeaderboardController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\TagController;
use Illuminate\Support\Facades\Route;


require __DIR__.'/adminDashboard.php';
require __DIR__.'/auth.php';

Route::get('/', HomeController::class);

Route::group(['prefix' => 'user', 'as' => 'user.'], function(){
    Route::get('/{user}/{username}/profile', [ProfileController::class, 'index'])->name('index');
    Route::middleware('auth')->group(function() {
        Route::get('/{user}/{username}/profile/update-profile', [ProfileController::class, 'updateProfile'])->name('updateProfile');
        Route::put('/{user}/{username}/profile/update-profile', [ProfileController::class, 'updateProfileStore'])->name('updateProfileStore');
        Route::get('/{user}/{username}/profile/change-password', [ProfileController::class, 'changePassword'])->name('changePassword');
        Route::put('/{user}/{username}/profile/change-password', [ProfileController::class, 'changePasswordStore'])->name('changePasswordStore');
    });
    Route::get('/{user}/{username}/activity/summary', [ProfileController::class, 'activity'])->name('activity');
    Route::get('/{user}/{username}/activity/question', [ProfileController::class, 'question'])->name('question');
    Route::get('/{user}/{username}/activity/answer', [ProfileController::class, 'answer'])->name('answer');
    Route::get('/{user}/{username}/activity/votes', [ProfileController::class, 'votes'])->name('votes');
    Route::get('/{user}/{username}/activity/comment', [ProfileController::class, 'comment'])->name('comment');
    Route::get('/{user}/{username}/activity/likes-question', [ProfileController::class, 'likesQuestion'])->name('likesQuestion');
    Route::get('/{user}/{username}/activity/likes-answer', [ProfileController::class, 'likesAnswer'])->name('likesAnswer');
});

Route::group(['prefix' => 'question', 'as' => 'question.'], function(){
    Route::get('/', [QuestionController::class, 'index'])->name('index');
    Route::get('/{question}/{slug}', [QuestionController::class, 'show'])->name('show');
    Route::get('/search', [QuestionController::class, 'search'])->name('search');
    Route::middleware('auth')->group(function() {
        Route::get('/ask-question', [QuestionController::class, 'askQuestion'])->name('askQuestion');
        Route::post('/ask-question', [QuestionController::class, 'askQuestionStore'])->name('askQuestionStore');
        Route::get('/{question}/{slug}/edit', [QuestionController::class, 'edit'])->name('edit');
        Route::put('/{question}/{slug}/update', [QuestionController::class, 'update'])->name('update');
        Route::put('/{question}/question-votes-count', [QuestionController::class, 'votesCount'])->name('votesCount');
        Route::put('/{question}/question-like', [QuestionController::class, 'like'])->name('like');
        Route::delete('/{question}/{slug}/delete', [QuestionController::class, 'destroy'])->name('destroy');
        Route::get('/{question}/{slug}/report', [QuestionController::class, 'report'])->name('report');
        Route::post('/{question}/{slug}/report', [QuestionController::class, 'reportStore'])->name('reportStore');
        Route::get('/{question}/{slug}/report/{report}/thank-you', [QuestionController::class, 'reportCallback'])->name('reportCallback');
    });
});

Route::group(['as' => 'answer.'], function(){
    Route::post('/answer/{question}/store', [AnswerController::class, 'store'])->name('store');
    Route::middleware('auth')->group(function() {
        Route::post('/answer/{answer}/comment', [AnswerController::class, 'commentStore'])->name('comment');
        Route::get('/question/{question}/{slug}/answer/{answer}/edit', [AnswerController::class, 'edit'])->name('edit');
        Route::put('/question/{question}/{slug}/answer/{answer}/update', [AnswerController::class, 'update'])->name('update');
        Route::put('/answer/{answer}/answer-votes-count', [AnswerController::class, 'votesCount'])->name('votesCount');
        Route::put('/answer/{answer}/answer-like', [AnswerController::class, 'like'])->name('like');
        Route::put('/answer/{answer}/best-answer', [AnswerController::class, 'bestAnswer'])->name('bestAnswer');
        Route::delete('/answer/{answer}/answer/delete', [AnswerController::class, 'destroy'])->name('destroy');
        Route::get('/answer/{answer}/report', [AnswerController::class, 'report'])->name('report');
        Route::post('/answer/{answer}/report', [AnswerController::class, 'reportStore'])->name('reportStore');
        Route::get('/answer/{answer}/report/{report}/thank-you', [AnswerController::class, 'reportCallback'])->name('reportCallback');
    });
    Route::get('/question/{question}/{slug}/answer/{answer}/comment', [AnswerController::class, 'answerComment'])->name('allComment');
});

Route::group(['prefix' => 'tag', 'as' => 'tag.'], function(){
    Route::get('/', [TagController::class, 'index'])->name('index');
    Route::get('/{tag}/questions', [TagController::class, 'questionByTag'])->name('questionByTag');
    Route::put('/{tag}/update', [TagController::class, 'update'])->name('update');
    Route::delete('/{tag}/delete', [TagController::class, 'destroy'])->name('destroy');
});

Route::group(['prefix' => 'leaderboard', 'as' => 'leaderboard.'], function(){
    Route::get('/', [LeaderboardController::class, 'index'])->name('index');
});

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    use HasFactory;
    protected $guarded = ['id'];

    public function getRouteKeyName()
    {
        return 'tag';
    }

    public function setTagAttribute($value)
    {
        return $this->attributes['tag'] = strtolower($value);
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function __invoke()
    {
        $meta = [
            'url' => url('/'),
            'title' => 'Curious about something?',
            'description' => 'Ask everything on FRAGE.'
        ];

        return view('home.index', compact('meta'));
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use App\Models\Tag;
use App\Services\LeaderboardService;
use App\Services\QuestionService;
use App\Services\TagServices;
use Illuminate\Http\Request;

class TagController extends Controller
{
    protected $tagService;
    protected $leaderboardService;
    protected $questionService;
    public function __construct(TagServices $tagService, LeaderboardService $leaderboardService, QuestionService $questionService)
    {
        $this->tagService = $tagService;
        $this->leaderboardService = $leaderboardService;
        $this->questionService = $questionService;
    }

    public function index()
    {
        $tags = Tag::latest()->paginate(20);

        $meta = [
            'url' => route('tag.index'),
            'title' => 'All Tags',
            'description' => 'Using the right tags makes it easier for others to find and answer your question.'
        ];

        return view('home.tag.index', compact('tags', 'meta'));
    }

    public function questionByTag(Tag $tag)
    {
        $questions = $this->tagService->questionFilter($tag);
        $count = $this->tagService->questionCount($tag);
        $leaderboard = $this->leaderboardService->leaderboard();
        $relatedTags = $this->questionService->relatedTags();

        $meta = [
            'url' => route('tag.questionByTag', $tag->tag),
            'title' => 'Question',
            'description' => 'Question by Tag : ' .$tag->tag
        ];
        
        return view('home.tag.question-by-tag', compact('tag', 'questions', 'count', 'leaderboard', 'relatedTags', 'meta'));
    }

    public function update(Tag $tag, Request $request)
    {
        return $this->tagService->updateTag($tag, $request);
    }

    public function destroy(Tag $tag)
    {   
        return $this->tagService->deleteTag($tag);
    }
}

resources/views/home/tag/_question.blade.php
<div class="question-content">
    <div class="row">
        <div class="col-md-2 col-12 detail-question"> 
            <p class="m-0">{{ $question->vote }} votes</p>
            <p class="m-0 {{ $question->answer->count() > 0 ? 'answer' : '' }} {{ $question->hasBestAnswer($question) == true ? 'best-answer' : '' }}">
                @if ($question->hasBestAnswer($question) == true)
                    <i class="fa-solid fa-check"></i>
                @endif
                {{ $question->answer->count() }} {{ $question->answer->count() > 9 ? 'answ...' : 'answers' }}
            </p>
            <p class="m-0">{{ $question->view_count }} views</p>
        </div>
        <div class="col-md-10 col-12 the-question">
            <p class="m-0 question-title"><a href="{{ route('question.show', [$question->id, $question->slug]) }}">{{ $question->title }}</a></p>
            <p>{{ str_replace('&nbsp;', ' ', $question->excerpt) }}</p>
            <div class="question-tag">
                @foreach ($question['tag'] as $tag)
                    <a href="{{ route('tag.questionByTag', $tag['tag']) }}" class="mr-1">{{ $tag['tag'] }}</a>
                @endforeach
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-12 d-flex justify-content-end user-info">
            <div>
                <p class="m-0">
                    @if ($question->user->oauth_picture !== null)
                        <img src="{{ $question->user->oauth_picture }}" alt="..." width="20px" height="20px">
                    @else
                        <img src="{{ $question->user->picture ? asset('assets/profile-picture/'. $question->user->picture) : asset('assets/profile-picture/default.png') }}" alt="..." width="20px" height="20px">
                    @endif
                    <a href="{{ route('user.index', [$question->user->id, $question->user->username]) }}">{{ $question->user->name }}</a> asked {{ $question->created_at->diffForHumans() }}
                </p>
                <p class="m-0 pl-4 trophy badges">
                    @foreach ($leaderboard as $user)
                        @if ($user['id'] == $question->user->id)
                            @if ($user['rank'] == 1)
                                <i class="rank-1 fa-solid fa-trophy" title="rank {{ $user['rank'] }} on leaderboard"></i>
                            @elseif($user['rank'] == 2)
                                <i class="rank-2 fa-solid fa-trophy" title="rank {{ $user['rank'] }} on leaderboard"></i>
                            @elseif($user['rank'] == 3)
                                <i class="rank-3 fa-solid fa-trophy" title="rank {{ $user['rank'] }} on leaderboard"></i>
                            @else
                                <i class="medal fa-solid fa-medal" title="rank {{ $user['rank'] }} on leaderboard"></i>
                            @endif

                            @if ($user['best_answer_count'] >= 10)
                                @if ($user['best_answer_count'] >= 100)
                                    <i class="gold fa-solid fa-award" title="get {{ $user['best_answer_count'] }} best answer"></i>
                                @elseif($user['best_answer_count'] >= 50)
                                    <i class="silver fa-solid fa-award" title="get {{ $user['best_answer_count'] }} best answer"></i>
                                @else
                                    <i class="bronze fa-solid fa-award" title="get {{ $user['best_answer_count'] }} best answer"></i>
                                @endif
                            @endif
                        @endif
                    @endforeach
                </p>
            </div>
        </div>
    </div>
</div>

resources/views/home/tag/index.blade.php
@extends('home.layouts.main')
@section('content')
    <div class="all-tags">
        <h3>All Tags</h3>
        <p class="m-0">A tag is a keyword or label that categorizes your question with other, similar questions.</p>
        <p class="m-0">Using the right tags makes it easier for others to find and answer your question.</p>

        <div class="row tags">
            @foreach ($tags as $tag)
                <div class="col-md-3 col-6 this-tag">
                    <div class="card">
                        <div class="tag">
                            <a href="{{ route('tag.questionByTag', $tag->tag) }}" class="m-0 tag-name">{{ $tag->tag }}</a>
                            <p class="m-0 question-count">{{ $tag->count }} times used in question</p>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
    
    {{-- pagination --}}
    <div class="mt-4 pagination">
        {{ $tags->links() }}
    </div>
    
@endsection

resources/views/home/tag/question-by-tag.blade.php
@extends('home.layouts.main')
@section('content')
    <div class="row mb-4">
        <div class="col-md-8 col-12">
            <div class="question-ask"> 
                <h3 class="mb-4 tag-title">Questions by tag <a href="#" class="m-0 tag-name">{{ $tag->tag }}</a></h3>
                <h5 class="mb-4"><a href="{{ route('question.askQuestion') }}" class="btn btn-primary">Ask Question</a></h5>
            </div>
            <div class="row mb-3">
                <div class="col-md-4 col-3 question-total">
                    <p class="m-0">{{ $count }} Questions</p>
                </div>
                <div class="col-md-8 col-9 d-flex justify-content-end question-filter">
                    <a href="{{ route('tag.questionByTag', [$tag->tag, 'newest']) }}" class="{{ request()->has('newest') ? 'active' : '' }}">Newest</a>
                    <a href="{{ route('tag.questionByTag', [$tag->tag, 'mostPopular']) }}" class="{{ request()->has('mostPopular') ? 'active' : '' }}">Most Popular</a>
                    <a href="{{ route('tag.questionByTag', [$tag->tag, 'unanswered']) }}" class="{{ request()->has('unanswered') ? 'active' : '' }}">Unanswered</a>
                    <a href="{{ route('tag.questionByTag', [$tag->tag, 'unsolved']) }}" class="{{ request()->has('unsolved') ? 'active' : '' }}">Unsolved</a>
                    <a href="{{ route('tag.questionByTag', [$tag->tag, 'solved']) }}" class="{{ request()->has('solved') ? 'active' : '' }}">Solved</a>
                </div>
            </div>
    
            {{-- question --}}
            @if ($count == 0)
                <div class="question-content">
                    <p>No questions records...</p>
                </div>
            @endif

            @foreach ($questions as $question)
                @if (request()->has('unsolved'))
                    @if ($question->hasBestAnswer($question) == false)
                        @include('home.tag._question')
                    @endif
                @elseif (request()->has('solved'))
                    @if ($question->hasBestAnswer($question))
                        @include('home.tag._question')
                    @endif
                @else
                    @include('home.tag._question')
                @endif
            @endforeach
            
            {{-- pagination --}}
            <div class="mt-5 pagination">
                {{ $questions->links() }}
            </div>
    
        </div>
        <div class="col-md-4 col-12 most-used-tags">
            <div class="card">
                <div class="card-body">
                <h6 class="card-title mb-3">Most Used Tags</h6>
                    @foreach ($relatedTags as $tag)
                        <div class="tag p-0 mb-2">
                            <a href="{{ route('tag.questionByTag', $tag->tag) }}" class="m-0 tag-name">{{ $tag->tag }}</a> <span class="ml-1"><i class="fa-solid fa-xmark" style="font-size: 10px"></i> {{ $tag->count }}</span>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
    
@endsection