routes/web.php
<?php

use App\Http\Controllers\AnswerController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LeaderboardController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\TagController;
use Illuminate\Support\Facades\Route;


require __DIR__.'/adminDashboard.php';
require __DIR__.'/auth.php';

Route::get('/', HomeController::class);

Route::group(['prefix' => 'user', 'as' => 'user.'], function(){
    Route::get('/{user}/{username}/profile', [ProfileController::class, 'index'])->name('index');
    Route::middleware('auth')->group(function() {
        Route::get('/{user}/{username}/profile/update-profile', [ProfileController::class, 'updateProfile'])->name('updateProfile');
        Route::put('/{user}/{username}/profile/update-profile', [ProfileController::class, 'updateProfileStore'])->name('updateProfileStore');
        Route::get('/{user}/{username}/profile/change-password', [ProfileController::class, 'changePassword'])->name('changePassword');
        Route::put('/{user}/{username}/profile/change-password', [ProfileController::class, 'changePasswordStore'])->name('changePasswordStore');
    });
    Route::get('/{user}/{username}/activity/summary', [ProfileController::class, 'activity'])->name('activity');
    Route::get('/{user}/{username}/activity/question', [ProfileController::class, 'question'])->name('question');
    Route::get('/{user}/{username}/activity/answer', [ProfileController::class, 'answer'])->name('answer');
    Route::get('/{user}/{username}/activity/votes', [ProfileController::class, 'votes'])->name('votes');
    Route::get('/{user}/{username}/activity/comment', [ProfileController::class, 'comment'])->name('comment');
    Route::get('/{user}/{username}/activity/likes-question', [ProfileController::class, 'likesQuestion'])->name('likesQuestion');
    Route::get('/{user}/{username}/activity/likes-answer', [ProfileController::class, 'likesAnswer'])->name('likesAnswer');
});

Route::group(['prefix' => 'question', 'as' => 'question.'], function(){
    Route::get('/', [QuestionController::class, 'index'])->name('index');
    Route::get('/{question}/{slug}', [QuestionController::class, 'show'])->name('show');
    Route::get('/search', [QuestionController::class, 'search'])->name('search');
    Route::middleware('auth')->group(function() {
        Route::get('/ask-question', [QuestionController::class, 'askQuestion'])->name('askQuestion');
        Route::post('/ask-question', [QuestionController::class, 'askQuestionStore'])->name('askQuestionStore');
        Route::get('/{question}/{slug}/edit', [QuestionController::class, 'edit'])->name('edit');
        Route::put('/{question}/{slug}/update', [QuestionController::class, 'update'])->name('update');
        Route::put('/{question}/question-votes-count', [QuestionController::class, 'votesCount'])->name('votesCount');
        Route::put('/{question}/question-like', [QuestionController::class, 'like'])->name('like');
        Route::delete('/{question}/{slug}/delete', [QuestionController::class, 'destroy'])->name('destroy');
        Route::get('/{question}/{slug}/report', [QuestionController::class, 'report'])->name('report');
        Route::post('/{question}/{slug}/report', [QuestionController::class, 'reportStore'])->name('reportStore');
        Route::get('/{question}/{slug}/report/{report}/thank-you', [QuestionController::class, 'reportCallback'])->name('reportCallback');
    });
});

Route::group(['as' => 'answer.'], function(){
    Route::post('/answer/{question}/store', [AnswerController::class, 'store'])->name('store');
    Route::middleware('auth')->group(function() {
        Route::post('/answer/{answer}/comment', [AnswerController::class, 'commentStore'])->name('comment');
        Route::get('/question/{question}/{slug}/answer/{answer}/edit', [AnswerController::class, 'edit'])->name('edit');
        Route::put('/question/{question}/{slug}/answer/{answer}/update', [AnswerController::class, 'update'])->name('update');
        Route::put('/answer/{answer}/answer-votes-count', [AnswerController::class, 'votesCount'])->name('votesCount');
        Route::put('/answer/{answer}/answer-like', [AnswerController::class, 'like'])->name('like');
        Route::put('/answer/{answer}/best-answer', [AnswerController::class, 'bestAnswer'])->name('bestAnswer');
        Route::delete('/answer/{answer}/answer/delete', [AnswerController::class, 'destroy'])->name('destroy');
        Route::get('/answer/{answer}/report', [AnswerController::class, 'report'])->name('report');
        Route::post('/answer/{answer}/report', [AnswerController::class, 'reportStore'])->name('reportStore');
        Route::get('/answer/{answer}/report/{report}/thank-you', [AnswerController::class, 'reportCallback'])->name('reportCallback');
    });
    Route::get('/question/{question}/{slug}/answer/{answer}/comment', [AnswerController::class, 'answerComment'])->name('allComment');
});

Route::group(['prefix' => 'tag', 'as' => 'tag.'], function(){
    Route::get('/', [TagController::class, 'index'])->name('index');
    Route::get('/{tag}/questions', [TagController::class, 'questionByTag'])->name('questionByTag');
    Route::put('/{tag}/update', [TagController::class, 'update'])->name('update');
    Route::delete('/{tag}/delete', [TagController::class, 'destroy'])->name('destroy');
});

Route::group(['prefix' => 'leaderboard', 'as' => 'leaderboard.'], function(){
    Route::get('/', [LeaderboardController::class, 'index'])->name('index');
});

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function __invoke()
    {
        $meta = [
            'url' => url('/'),
            'title' => 'Curious about something?',
            'description' => 'Ask everything on FRAGE.'
        ];

        return view('home.index', compact('meta'));
    }
}

app/Http/Controllers/ProfileController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\User\ChangePasswordRequest;
use App\Http\Requests\User\UpdateProfileRequest;
use App\Models\User;
use App\Services\LeaderboardService;
use App\Services\ProfileService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\ValidationException;

class ProfileController extends Controller
{
    protected $leaderboardService;
    protected $profileService;
    public function __construct(LeaderboardService $leaderboardService, ProfileService $profileService)
    {
        $this->leaderboardService = $leaderboardService;
        $this->profileService = $profileService;
    }

    public function index(User $user, $username)
    {
        $reach = $this->profileService->reach($user);
        $topQuestion = $user->question->sortByDesc('vote')->take(10);
        $topAnswer = $user->answer->sortByDesc('vote')->take(10);
        $leaderboard = $this->leaderboardService->leaderboard()->where('id', $user->id)->first();

        $meta = [
            'url' => route('user.index', [$user, $username]),
            'title' => $user->name,
            'description' => 'Profile'
        ];
        
        return view('home.profile.index', compact('user', 'reach', 'topQuestion', 'topAnswer', 'leaderboard', 'meta'));
    }

    public function updateProfile(User $user, $username)
    {
        $meta = [
            'url' => route('user.index', [$user, $username]),
            'title' => $user->name,
            'description' => 'Profile'
        ];

        return view('home.profile.update-profile', compact('user', 'meta'));
    }

    public function updateProfileStore(User $user, $username, UpdateProfileRequest $request)
    {
        $this->profileService->updatingProfile($user, $request);

        return redirect()->route('user.index', [$user->id, $user->username]);
    }

    public function changePassword(User $user, $username)
    {
        $meta = [
            'url' => route('user.index', [$user, $username]),
            'title' => $user->name,
            'description' => 'Profile'
        ];

        return view('home.profile.change-password', compact('user', 'meta'));
    }

    public function changePasswordStore(User $user, $username, ChangePasswordRequest $request)
    {
        if (Hash::check($request->old_password, $user->password)) {
            $user->update($request->only('password'));

            return redirect()->route('user.index', [$user->id, $username]);
        }

        throw ValidationException::withMessages([
            'old_password' => 'Old password do not match'
        ]);

    }

    public function activity(User $user, $username)
    {
        $meta = [
            'url' => route('user.activity', [$user, $username]),
            'title' => $user->name,
            'description' => 'Summary'
        ];

        return view('home.profile.activity', compact('user', 'meta'));
    }

    public function question(User $user, $username)
    {
        $questions = $user->question()->latest()->paginate(20);

        $meta = [
            'url' => route('user.question', [$user, $username]),
            'title' => $user->name,
            'description' => 'Question'
        ];

        return view('home.profile.question', compact('user', 'questions', 'meta'));
    }

    public function answer(User $user, $username)
    {
        $answers = $user->answer()->latest()->paginate(20);

        $meta = [
            'url' => route('user.answer', [$user, $username]),
            'title' => $user->name,
            'description' => 'Answer'
        ];

        return view('home.profile.answer', compact('user', 'answers', 'meta'));
    }

    public function comment(User $user, $username)
    {
        $comments = $user->answerComment()->latest()->paginate(20);

        $meta = [
            'url' => route('user.comment', [$user, $username]),
            'title' => $user->name,
            'description' => 'Comment'
        ];

        return view('home.profile.comment', compact('user', 'comments', 'meta'));
    }
    
    public function votes(User $user, $username)
    {
        $questionVotesUp = $user->questionVotes()->where('option', 'votes-up')->latest()->paginate(20);
        $questionVotesDown = $user->questionVotes()->where('option', 'votes-down')->latest()->paginate(20);

        $answerVotesUp = $user->answerVotes()->where('option', 'votes-up')->latest()->paginate(20);
        $answerVotesDown = $user->answerVotes()->where('option', 'votes-down')->latest()->paginate(20);

        $meta = [
            'url' => route('user.votes', [$user, $username]),
            'title' => $user->name,
            'description' => 'Votes'
        ];

        return view('home.profile.votes', compact('user', 'questionVotesUp', 'questionVotesDown', 'answerVotesUp', 'answerVotesDown', 'meta'));
    }

    public function likesQuestion(User $user, $username)
    {
        $likesQuestion = $user->questionLike()->where('status', true)->latest()->paginate(20);

        $meta = [
            'url' => route('user.likesQuestion', [$user, $username]),
            'title' => $user->name,
            'description' => 'Likes Question'
        ];

        return view('home.profile.likes-question', compact('user', 'likesQuestion', 'meta'));
    }

    public function likesAnswer(User $user, $username)
    {
        $likesAnswer = $user->answerLike()->where('status', true)->latest()->paginate(20);

        $meta = [
            'url' => route('user.likesAnswer', [$user, $username]),
            'title' => $user->name,
            'description' => 'Likes Answer'
        ];

        return view('home.profile.likes-answer', compact('user', 'likesAnswer', 'meta'));
    }
}

resources/views/home/profile/answer.blade.php
@extends('home.layouts.main')
@section('content')

    @include('home.profile.profile-picture')

    <div class="my-4">
        <a href="{{ route('user.index', [$user->id, $user->username]) }}" class="btn btn-sm btn-outline-secondary">Profile</a>
        <a href="{{ route('user.activity', [$user->id, $user->username]) }}" class="btn btn-sm btn-primary">Activity</a>
    </div>
    
    <div class="mt-4 row">
        <div class="col-md-2 col-12 activity-tab">
            @include('home.profile.activity-tab')
        </div>

        <div class="col-md-10 col-12 answer-box">
            <div class="col-md-12 col-12">
                <h5>Answer</h5>
                <div class="card">
                    <div class="card-body pt-0">

                        @if ($answers->first() == null)
                            <p class="m-0">Don't have answer record yet.</p>
                        @endif
                        @foreach ($answers as $answer)
                            <div class="user-answer row">
                                <div class="col-md-9 col-8">
                                    
                                    @if ($answer->bestAnswer()->where('answer_id', $answer->id)->first() !== null)
                                        @if ($answer->bestAnswer()->where('answer_id', $answer->id)->first()['check'] == true)
                                            <p class="score best-answer {{ $answer->vote > 0 ? 'votes-up' : '' }} {{ $answer->vote < 0 ? 'votes-down' : '' }}">{{ $answer->vote }}</p>
                                        @else    
                                            <p class="score {{ $answer->vote > 0 ? 'votes-up' : '' }} {{ $answer->vote < 0 ? 'votes-down' : '' }}">{{ $answer->vote }}</p>
                                        @endif
                                    @else
                                        <p class="score {{ $answer->vote > 0 ? 'votes-up' : '' }} {{ $answer->vote < 0 ? 'votes-down' : '' }}">{{ $answer->vote }}</p>
                                    @endif
                                    
                                    <a href="{{ route('answer.allComment', [$answer->question_id, $answer->question->slug, $answer->id]) }}">{{  str_replace('&nbsp;', ' ', $answer->excerpt)  }}</a>
                                </div>
                                <div class="col-md-3 col-4 text-right">
                                    <p>{{ $answer->created_at->format('d F Y') }}</p>
                                </div>
                            </div>
                        @endforeach

                    </div>
                </div>

                <div class="mt-4 pagination">
                    {{ $answers->links() }}
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/home/profile/change-password.blade.php
@extends('home.layouts.main')
@section('content')

    <div class="change-password-box">
        @if (auth()->user()->oauth)
            <div class="col-md-5">
                <div class="card error-change-password">
                    <div class="card-body">
                        <h5>Ups...</h5>
                        <p class="card-text m-0">You are login with {{ auth()->user()->oauth }}.</p>
                        <p class="card-text">You can't change your password.</p>
                        <a href="{{ route('user.index', [$user->id, $user->username]) }}">Back to profile</a>
                    </div>
                </div>
            </div>
        @else   
            <h3>Change Password</h3>

            <div class="row mt-4">
                <div class="col-md-5 col-12 change-password">
                    <form action="{{ route('user.changePasswordStore', [$user->id, $user->username]) }}" method="post">
                    @csrf 
                    @method('put')
                        <div class="py-1">
                            <label for="old_password" class="form-label">Old Password</label>
                            <input type="password" id="old_password" name="old_password" class="form-control @error('old_password') is-invalid @enderror">
                            @error('old_password')
                                <div class="is-invalid text-danger">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <div class="py-1">
                            <label for="password" class="form-label">New Password</label>
                            <input type="password" id="password" name="password" class="form-control @error('password') is-invalid @enderror">
                            @error('password')
                                <div class="is-invalid text-danger">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <div class="py-1">
                            <label for="password_confirmation" class="form-label">Confirm New Password</label>
                            <input type="password" id="password_confirmation" name="password_confirmation" class="form-control @error('password_confirmation') is-invalid @enderror">
                            @error('password_confirmation')
                                <div class="is-invalid text-danger">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <input style="display: none" type="file" id="picture" name="picture" onchange="previewImage()">
                        <div class="d-flex justify-content-end">
                            <a href="{{ route('user.index', [$user->id, $user->username]) }}" class="btn btn-sm btn-outline-secondary mt-3 mr-2">Cancel</a>
                            <button type="submit" class="btn btn-sm btn-primary mt-3">Confirm Change</button>
                        </div>
                    </form>
                </div>
            </div> 
        @endif
    </div>
    
@endsection

resources/views/home/profile/index.blade.php
@extends('home.layouts.main')
@section('content')

    <div class="profile-index">
        @include('home.profile.profile-picture')
    
        <div class="profile-activity-button">
            <a href="{{ route('user.index', [$user->id, $user->username]) }}" class="btn btn-sm btn-primary">Profile</a>
            <a href="{{ route('user.activity', [$user->id, $user->username]) }}" class="btn btn-sm btn-outline-secondary">Activity</a>
        </div>
        
        <div class="mt-4 row">
            <div class="col-md-3 col-12 stats">
                <h5>Stats</h5>
                <div class="card">
                    <div class="card-body row">
                        <div class="col-md-6 col-6">
                            @if ($leaderboard == null)
                                <h6 class="m-0">-</h6>
                            @else
                                <h6 class="m-0">#{{ $leaderboard['rank'] }}</h6> 
                            @endif
                            <p>rank</p>
                        </div>
                        <div class="col-md-6 col-6">
                            <h6 class="m-0">{{ number_format($reach) }}</h6>
                            <p>reach</p>
                        </div>
                        <div class="col-md-6 col-6">
                            <h6 class="m-0">{{ number_format($user->question->count()) }}</h6>
                            <p class="m-0">questions</p>
                        </div>
                        <div class="col-md-6 col-6">
                            <h6 class="m-0">{{ number_format($user->answer->count()) }}</h6>
                            <p class="m-0">answers</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-9 col-12">
                <div class="col-md-12 col-12 badges-box">
                    <h5>Badges</h5>
                    <div class="card">
                        <div class="card-body">
                            
                            @if ($leaderboard !== null)
                                @if ($leaderboard['best_answer_count'] >= 10)
                                    <div class="row mb-4">
                                        <div class="col-md-2 col-2 badges text-center">
                                            @if ($leaderboard['best_answer_count'] >= 100)
                                                <i class="gold fa-solid fa-award"></i>
                                            @elseif($leaderboard['best_answer_count'] >= 50)
                                                <i class="silver fa-solid fa-award"></i>
                                            @else
                                                <i class="bronze fa-solid fa-award"></i>
                                            @endif
                                        </div>
                                        <div class="col-md-10 col-10 row badges-detail">
                                            <div class="col-md-12">
                                                @if ($leaderboard['best_answer_count'] >= 100)
                                                    <h5>Gold badges</h5>
                                                @elseif($leaderboard['best_answer_count'] >= 50)
                                                    <h5>Silver badges</h5>
                                                @else
                                                    <h5>Bronze Badges</h5>
                                                @endif
                                            </div>
                                            <div class="col-md-12">
                                                <p><i class="fa-solid fa-check"></i> Solving question more than {{ $leaderboard['best_answer_count'] }} times</p>
                                            </div>
                                        </div>
                                    </div>
                                @endif
                            @else
                                <p class="m-0">Don't have Badges record yet.</p>
                            @endif
                            
                            @if ($leaderboard !== null)
                                <div class="row">
                                    <div class="col-md-2 col-2 trophy text-center">
                                        @if ($leaderboard['rank'] == 1)
                                            <i class="rank-1 fa-solid fa-trophy"></i>
                                        @elseif($leaderboard['rank'] == 2)
                                            <i class="rank-2 fa-solid fa-trophy"></i>
                                        @elseif($leaderboard['rank'] == 3)
                                            <i class="rank-3 fa-solid fa-trophy"></i>
                                        @else
                                            <i class="medal fa-solid fa-medal"></i>
                                        @endif
                                    </div>
                                    <div class="col-md-10 col-10 row badges-detail">
                                        <div class="col-md-12">
                                            @if ($leaderboard['rank'] == 1)
                                                <h5>Gold trophy</h5>
                                            @elseif($leaderboard['rank'] == 2)
                                                <h5>Silver trophy</h5>
                                            @elseif($leaderboard['rank'] == 3)
                                                <h5>Bronze trophy</h5>
                                            @else
                                                <h5>Medal</h5>
                                            @endif
                                        </div>
                                        <div class="col-md-12">
                                            <p><i class="fa-solid fa-hashtag"></i>{{ $leaderboard['rank'] }} rank on Leaderboard</p>
                                        </div>
                                    </div>
                                </div>
                            @endif
                            
                        </div>
                    </div>
                </div>
                
                <div class="col-md-12 col-12 mt-4 top-question-box">
                    <h5>Top Question</h5>
                    <div class="card">
                        <div class="card-body pt-0">

                            @if ($topQuestion->first() == null)
                                <p class="m-0">Don't have question record yet.</p>
                            @endif
                            @foreach ($topQuestion as $question)
                                <div class="top-question row">
                                    <div class="col-md-9 col-8">
                                        <p class="score {{ $question->hasBestAnswer($question) == true ? 'solved' : '' }} {{ $question->vote > 0 ? 'votes-up' : '' }} {{ $question->vote < 0 ? 'votes-down' : '' }}">{{ $question->vote }}</p>
                                        <a href="{{ route('question.show', [$question->id, $question->slug]) }}">{{ $question->title }}</a>
                                    </div>
                                    <div class="col-md-3 col-4 text-right">
                                        <p>{{ $question->created_at->format('d F Y') }}</p>
                                    </div>
                                </div>
                            @endforeach
                            
                        </div>
                    </div>
                </div>
                
                <div class="col-md-12 col-12 mt-4 top-answer-box">
                    <h5>Top Answer</h5>
                    <div class="card">
                        <div class="card-body pt-0">

                            @if ($topAnswer->first() == null)
                                <p class="m-0">Don't have answer record yet.</p>
                            @endif
                            @foreach ($topAnswer as $answer)
                                <div class="top-answer row">
                                    <div class="col-md-9 col-8">
                                        
                                        @if ($answer->bestAnswer()->where('answer_id', $answer->id)->first() !== null)
                                            @if ($answer->bestAnswer()->where('answer_id', $answer->id)->first()['check'] == true)
                                                <p class="score best-answer {{ $answer->vote > 0 ? 'votes-up' : '' }} {{ $answer->vote < 0 ? 'votes-down' : '' }}">{{ $answer->vote }}</p>
                                            @else    
                                                <p class="score {{ $answer->vote > 0 ? 'votes-up' : '' }} {{ $answer->vote < 0 ? 'votes-down' : '' }}">{{ $answer->vote }}</p>
                                            @endif
                                        @else
                                            <p class="score {{ $answer->vote > 0 ? 'votes-up' : '' }} {{ $answer->vote < 0 ? 'votes-down' : '' }}">{{ $answer->vote }}</p>
                                        @endif
                                        
                                        <a href="{{ route('answer.allComment', [$answer->question_id, $answer->question->slug, $answer->id]) }}">{{  str_replace('&nbsp;', ' ', $answer->excerpt)  }}</a>
                                    </div>
                                    <div class="col-md-3 col-4 text-right">
                                        <p>{{ $answer->created_at->format('d F Y') }}</p>
                                    </div>
                                </div>
                            @endforeach
                            
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

@endsection

resources/views/home/profile/update-profile.blade.php
@extends('home.layouts.main')
@section('content')

    <div class="update-profile-box">
        <h3>Update Profile</h3>

        <div class="row mt-4">
            <div class="col-md-2 col-12 mt-3 change-picture">
                <div>
                    @if ($user->oauth_picture !== null)
                        <img src="{{ $user->oauth_picture }}" alt="..." width="130px" height="130px" class="img-preview">
                    @else
                        <img src="{{ $user->picture ? asset('assets/profile-picture/'. $user->picture) : asset('assets/profile-picture/default.png') }}" alt="..." width="130px" height="130px" class="img-preview">
                    @endif
                    <div class="change-picture-button">
                        <label for="picture" class="btn btn-sm btn-outline-secondary mt-3" style="cursor: pointer;">Change Picture</label>
                    </div>
                </div>
            </div>
            <div class="col-md-5 col-12 update-profile">
                <form action="{{ route('user.updateProfileStore', [$user->id, $user->username]) }}" method="post" enctype="multipart/form-data">
                @csrf 
                @method('put')
                    <div class="py-1">
                        <label for="name" class="form-label">Name</label>
                        <input type="text" id="name" name="name" class="form-control @error('name') is-invalid @enderror" value="{{ old('name', $user->name) }}">
                        @error('name')
                            <div class="is-invalid text-danger">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="py-1">
                        <label for="email" class="form-label">Email</label>
                        <input type="email" id="email" name="email" class="form-control @error('email') is-invalid @enderror" value="{{ old('name', $user->email) }}">
                        @error('email')
                            <div class="is-invalid text-danger">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <a href="{{ route('user.changePassword', [$user->id, $user->username]) }}">Change Password?</a>
                    <input style="display: none" type="file" id="picture" name="picture" onchange="previewImage()">
                    <input type="hidden" name="oauth_picture" value="{{ null }}">
                    <div class="d-flex justify-content-end">
                        <a href="{{ route('user.index', [$user->id, $user->username]) }}" class="btn btn-sm btn-outline-secondary mt-3 mr-2">Cancel</a>
                        <button type="submit" class="btn btn-sm btn-primary mt-3">Update</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

@push('script')
    <script>
        function previewImage() {
            const image = document.querySelector('#picture');
            const imgPreview = document.querySelector('.img-preview');

            imgPreview.style.display = 'block';

            const oFReader = new FileReader();
            oFReader.readAsDataURL(image.files[0]);

            oFReader.onload = function(oFREvent) {
                imgPreview.src = oFREvent.target.result;
            }
        }
    </script>
@endpush