routes/web.php
<?php

use App\Http\Controllers\AnswerController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LeaderboardController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\TagController;
use Illuminate\Support\Facades\Route;


require __DIR__.'/adminDashboard.php';
require __DIR__.'/auth.php';

Route::get('/', HomeController::class);

Route::group(['prefix' => 'user', 'as' => 'user.'], function(){
    Route::get('/{user}/{username}/profile', [ProfileController::class, 'index'])->name('index');
    Route::middleware('auth')->group(function() {
        Route::get('/{user}/{username}/profile/update-profile', [ProfileController::class, 'updateProfile'])->name('updateProfile');
        Route::put('/{user}/{username}/profile/update-profile', [ProfileController::class, 'updateProfileStore'])->name('updateProfileStore');
        Route::get('/{user}/{username}/profile/change-password', [ProfileController::class, 'changePassword'])->name('changePassword');
        Route::put('/{user}/{username}/profile/change-password', [ProfileController::class, 'changePasswordStore'])->name('changePasswordStore');
    });
    Route::get('/{user}/{username}/activity/summary', [ProfileController::class, 'activity'])->name('activity');
    Route::get('/{user}/{username}/activity/question', [ProfileController::class, 'question'])->name('question');
    Route::get('/{user}/{username}/activity/answer', [ProfileController::class, 'answer'])->name('answer');
    Route::get('/{user}/{username}/activity/votes', [ProfileController::class, 'votes'])->name('votes');
    Route::get('/{user}/{username}/activity/comment', [ProfileController::class, 'comment'])->name('comment');
    Route::get('/{user}/{username}/activity/likes-question', [ProfileController::class, 'likesQuestion'])->name('likesQuestion');
    Route::get('/{user}/{username}/activity/likes-answer', [ProfileController::class, 'likesAnswer'])->name('likesAnswer');
});

Route::group(['prefix' => 'question', 'as' => 'question.'], function(){
    Route::get('/', [QuestionController::class, 'index'])->name('index');
    Route::get('/{question}/{slug}', [QuestionController::class, 'show'])->name('show');
    Route::get('/search', [QuestionController::class, 'search'])->name('search');
    Route::middleware('auth')->group(function() {
        Route::get('/ask-question', [QuestionController::class, 'askQuestion'])->name('askQuestion');
        Route::post('/ask-question', [QuestionController::class, 'askQuestionStore'])->name('askQuestionStore');
        Route::get('/{question}/{slug}/edit', [QuestionController::class, 'edit'])->name('edit');
        Route::put('/{question}/{slug}/update', [QuestionController::class, 'update'])->name('update');
        Route::put('/{question}/question-votes-count', [QuestionController::class, 'votesCount'])->name('votesCount');
        Route::put('/{question}/question-like', [QuestionController::class, 'like'])->name('like');
        Route::delete('/{question}/{slug}/delete', [QuestionController::class, 'destroy'])->name('destroy');
        Route::get('/{question}/{slug}/report', [QuestionController::class, 'report'])->name('report');
        Route::post('/{question}/{slug}/report', [QuestionController::class, 'reportStore'])->name('reportStore');
        Route::get('/{question}/{slug}/report/{report}/thank-you', [QuestionController::class, 'reportCallback'])->name('reportCallback');
    });
});

Route::group(['as' => 'answer.'], function(){
    Route::post('/answer/{question}/store', [AnswerController::class, 'store'])->name('store');
    Route::middleware('auth')->group(function() {
        Route::post('/answer/{answer}/comment', [AnswerController::class, 'commentStore'])->name('comment');
        Route::get('/question/{question}/{slug}/answer/{answer}/edit', [AnswerController::class, 'edit'])->name('edit');
        Route::put('/question/{question}/{slug}/answer/{answer}/update', [AnswerController::class, 'update'])->name('update');
        Route::put('/answer/{answer}/answer-votes-count', [AnswerController::class, 'votesCount'])->name('votesCount');
        Route::put('/answer/{answer}/answer-like', [AnswerController::class, 'like'])->name('like');
        Route::put('/answer/{answer}/best-answer', [AnswerController::class, 'bestAnswer'])->name('bestAnswer');
        Route::delete('/answer/{answer}/answer/delete', [AnswerController::class, 'destroy'])->name('destroy');
        Route::get('/answer/{answer}/report', [AnswerController::class, 'report'])->name('report');
        Route::post('/answer/{answer}/report', [AnswerController::class, 'reportStore'])->name('reportStore');
        Route::get('/answer/{answer}/report/{report}/thank-you', [AnswerController::class, 'reportCallback'])->name('reportCallback');
    });
    Route::get('/question/{question}/{slug}/answer/{answer}/comment', [AnswerController::class, 'answerComment'])->name('allComment');
});

Route::group(['prefix' => 'tag', 'as' => 'tag.'], function(){
    Route::get('/', [TagController::class, 'index'])->name('index');
    Route::get('/{tag}/questions', [TagController::class, 'questionByTag'])->name('questionByTag');
    Route::put('/{tag}/update', [TagController::class, 'update'])->name('update');
    Route::delete('/{tag}/delete', [TagController::class, 'destroy'])->name('destroy');
});

Route::group(['prefix' => 'leaderboard', 'as' => 'leaderboard.'], function(){
    Route::get('/', [LeaderboardController::class, 'index'])->name('index');
});

app/Models/Answer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    use HasFactory;
    protected $guarded = ['id'];
    protected $with = ['user', 'answerLike', 'answerVotes', 'answerComment', 'answerReport'];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function question()
    {
        return $this->belongsTo(Question::class, 'question_id');
    }

    public function answerVotes()
    {
        return $this->hasMany(AnswerVotes::class, 'answer_id');
    }

    public function answerLike()
    {
        return $this->hasMany(AnswerLike::class, 'answer_id');
    }

    public function answerComment()
    {
        return $this->hasMany(AnswerComment::class, 'answer_id');
    }

    public function bestAnswer()
    {
        return $this->hasMany(BestAnswer::class, 'answer_id');
    }

    public function answerReport()
    {
        return $this->hasMany(AnswerReport::class, 'answer_id');
    }
}

app/Http/Controllers/AnswerController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\AnswerRequest;
use App\Http\Requests\CommentRequest;
use App\Http\Requests\ReportRequest;
use App\Models\Answer;
use App\Models\AnswerReport;
use App\Models\Question;
use App\Services\AnswerService;
use App\Services\LeaderboardService;
use App\Services\QuestionService;
use Illuminate\Http\Request;

class AnswerController extends Controller
{
    protected $answerService;
    protected $leaderboardService;
    protected $questionService;
    public function __construct(AnswerService $answerService, LeaderboardService $leaderboardService, QuestionService $questionService)
    {
        $this->answerService = $answerService;
        $this->leaderboardService = $leaderboardService;
        $this->questionService = $questionService;
    }

    public function store(Question $question, AnswerRequest $request)
    {
        $this->answerService->storingAnswer($question, $request);
        
        return redirect()->route('question.show', [$question->id, $question->slug]);
    }

    public function edit($question, $slug, Answer $answer)
    {
        $relatedQuestions = $this->questionService->relatedQuestions($answer->question);

        $meta = [
            'url' => route('question.show', [$answer->question->id, $answer->question->slug]),
            'title' => $answer->question->title,
            'description' => $answer->excerpt
        ];

        return view('home.answer.edit', compact('answer', 'relatedQuestions', 'meta'));
    }

    public function update($question, $slug, Answer $answer, AnswerRequest $request)
    {
        $this->answerService->updatingAnswer($answer, $request);

        return redirect()->route('question.show', [$answer->question->id, $answer->question->slug]);
    }
    
    public function commentStore(Answer $answer, CommentRequest $request)
    {   
        $this->answerService->storingComment($answer, $request);
        
        return response()->json([
            'user' => $answer->user,
            'comment' => $request->comment,
            'count' => $answer->answerComment->count() +1
        ], 200);
    }
    
    public function answerComment(Question $question, $slug, Answer $answer)
    {
        $bestAnswerCheck = $question->hasBestAnswer($question);
        $leaderboard = $this->leaderboardService->leaderboard();
        $relatedQuestions = $this->questionService->relatedQuestions($question);

        $meta = [
            'url' => route('answer.allComment', [$question, $slug, $answer]),
            'title' => $answer->question->title,
            'description' => $answer->excerpt
        ];

        return view('home.answer.comment', compact('answer', 'bestAnswerCheck', 'leaderboard', 'relatedQuestions', 'meta'));
    }

    public function votesCount(Answer $answer, Request $request)
    {  
        return $this->answerService->countingVotes($answer, $request);
    }

    public function like(Answer $answer)
    {
        return $this->answerService->updatingLikes($answer);
    }

    public function bestAnswer(Answer $answer)
    {
        $this->answerService->markAsBestAnswer($answer);

        return response()->json('check', 200);
    }

    public function destroy(Answer $answer)
    {   
        // delete answer image on storage
        $this->answerService->deleteAnswerImage($answer);

        $answer->delete();
        
        return response()->json([
            'answer_id' => $answer->id,
            'answer_count' => $answer->where('question_id', $answer->question->id)->count()
        ], 200);
    }

    public function report(Answer $answer)
    {
        $meta = [
            'url' => route('answer.report', $answer->id),
            'title' => 'Report Answer',
            'description' => $answer->excerpt
        ];

        return view('home.answer.report', compact('answer', 'meta'));
    }

    public function reportStore(Answer $answer, ReportRequest $request)
    {
        $report = $this->answerService->storingReport($answer, $request);

        return redirect()->route('answer.reportCallback', [$answer->id, $report->id]);
    }

    public function reportCallback($answer, $report)
    {
        $meta = [
            'url' => url('/'),
            'title' => 'Curious about something?',
            'description' => 'Ask everything on FRAGE.'
        ];

        return view('home.answer.report-callback', compact('meta'));
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function __invoke()
    {
        $meta = [
            'url' => url('/'),
            'title' => 'Curious about something?',
            'description' => 'Ask everything on FRAGE.'
        ];

        return view('home.index', compact('meta'));
    }
}

resources/views/home/answer/edit.blade.php
@extends('home.layouts.main')
@section('content')
    <div class="row">
        <div class="col-md-8 col-12">
            <div class="mb-3 back">
                <a class="text-secondary" href="{{ route('question.show', [$answer->question->id, $answer->question->slug]) }}"><h6><i class="fa-solid fa-arrow-left"></i> Back to main question</h6></a>
            </div>
            <div class="your-answer">
                <h5>Edit Your Answer</h5>
                <form action="{{ route('answer.update', [$answer->question->id, $answer->question->slug, $answer->id]) }}" method="POST" class="pt-2">
                    @csrf
                    @method('PUT')
                    <div class="mb-3">
                        <textarea name="answer" id="summernote" cols="100" rows="10">{!! $answer->answer !!}</textarea>
                    </div>
                    <button type="submit" class="btn btn-primary mt-2">Update your answer</button>
                </form>
            </div>
        </div>
        <div class="col-md-4 col-12 related">
            <div class="card question-interested">
                <div class="card-body">
                <h6 class="card-title mb-3">Questions Might You Interested</h6>
                    @foreach ($relatedQuestions as $question)
                        <div class="p-0 mb-2 top-question">
                            <p class="score {{ $question->hasBestAnswer($question) == true ? 'solved' : '' }} {{ $question->vote > 0 ? 'votes-up' : '' }} {{ $question->vote < 0 ? 'votes-down' : '' }}">{{ $question->vote }}</p>
                            <a href="{{ route('question.show', [$question->id, $question->slug]) }}" class="pl-2">{{ $question->title }}</a>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
@endsection

@push('script')
    <script>
        // summernote
        $('#summernote').summernote({
            tabsize: 2,
            height: 250,
            toolbar: [
                ['style', ['style']],
                ['font', ['bold', 'underline', 'clear']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['table', ['table']],
                ['insert', ['link', 'picture']],
            ],
            callback: {
                onImageUpload: function(files) {
                    for (let i = 0; i < files.length; i++) {
                        $.upload(files[i]);
                    }
                },
                onMediaDelete: function(target) {
                    $.delete(target[0].src);
                }
            }
        });

        $.upload = function(file) {
            let out = new formData();
            out.append('file', file, file.name);
            $.ajax({
                method: 'POST',
                contentType: false,
                cache: false,
                processData: false,
                data: out,
                success: function(img) {
                    $('#summernote').summernote('insertImage', img);
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    console.error(textStatus + " " + errorThrown);
                }
            });
        };

        $.delete = function(src) {
            $.ajax({
                method: 'POST',
                cache: false,
                data: {
                    src: src
                },
                success: function(response) {
                    console.log(response)
                }
            });
        };
    </script>    
@endpush

resources/views/home/answer/report-callback.blade.php
@extends('home.layouts.main')
@section('content')
    <div class="text-center mt-5 report-callback">
        <h2 style="color: #48A868"><i class="fa-solid fa-clipboard-check"></i></h2>
        <h3 style="color: #48A868">Thank you for your reporting!</h3>
        <h6 style="color: #48A868">We will take an action for this answer.</h6>
    </div>
    <div class="mt-5 text-center report-done">
        <a href="{{ route('question.index') }}" class="text-secondary">Done!</a>
    </div>
@endsection

resources/views/home/answer/report.blade.php
@extends('home.layouts.main')
@section('content')
    <div class="d-flex justify-content-center report-box">
        <div class="col-md-7">
            <h6 class="text-danger mb-3"><i class="fa-solid fa-flag"></i> Report this answer!</h6>
            <div class="card report">
                <div class="card-body">
                    <p class="text-danger">Please tell us why you report this answer.</p>
                    <form action="{{ route('answer.reportStore', $answer->id) }}" method="POST" class="mt-3">
                        @csrf
                        <div class="mb-3">
                            <textarea name="report_message" class="input-report" placeholder="Report message..."></textarea>
                        </div>
                        <div class="d-flex justify-content-end">
                            <a href="{{ url()->previous() }}" class="btn btn-link">Cancel</a>
                            <button type="submit" class="btn btn-sm btn-danger">Report!</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection